project_id = "ngwbpuxltyfweikdupoj"

[functions.ping]
verify_jwt = false

[functions.seedpacks]
verify_jwt = false


[functions.send-job-notification]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.weekly-kpi-digest]
verify_jwt = false



[functions.optimize-image]
verify_jwt = false

[functions.analyze-dispute]
verify_jwt = false

[functions.dispute-deadline-automation]
verify_jwt = false

[functions.generate-weekly-ai-report]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false